.TH MV_BINARY_BINARY_TREE 1
.SH NAME
mv_binary_binary_tree \- Binary binary tree
.\"
.SH SYNOPSIS
.B mv_binary_binary_tree
[ \fB\-a\fR \fIoption_1_value\fR ]
[ \fB\-\-option1=\fR\fIoption_1_value\fR ]
[ \fB\-b\fR \fIoption_2_value\fR ]
[ \fB\-\-option2=\fR\fIoption_2_value\fR ]
.IR file ...
.\"
.SH DESCRIPTION
.B mv_binary_binary_tree
Here is a longer description
.\"
.SH RETURN VALUE
The
.BR mv_binary_binary_tree ()
function returns a pointer to ...
.\"
.SH SEE ALSO
.BR manpagename (7)
for more information about something else.
